// AUTH
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE'
export const AUTH_SIGNUP_REQUEST = 'AUTH_SIGNUP_REQUEST'
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS'
export const AUTH_SIGNUP_FAILURE = 'AUTH_SIGNUP_FAILURE'
export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST'
export const AUTH_REMOVE_USER = 'AUTH_REMOVE_USER'

// THING
export const GET_USER_THING_REQUEST = 'GET_USER_THING_REQUEST'
export const GET_USER_THING_SUCCESS = 'GET_USER_THING_SUCCESS'
export const GET_USER_THING_FAILURE = 'GET_USER_THING_FAILURE'
export const CREATE_THING_REQUEST = 'CREATE_THING_REQUEST'
export const CREATE_THING_SUCCESS = 'CREATE_THING_SUCCESS'
export const CREATE_THING_FAILURE = 'CREATE_THING_FAILURE'
