// Track Component


// Release Component
export const ADD_BLANK_TRACK = 'ADD_BLANK_TRACK'
export const DROP_TRACK = 'DROP_TRACK'
export const UPDATE_DURATION = 'UPDATE_DURATION'
export const UPDATE_ARTIST_NAME = 'UPDATE_ARTIST_NAME'
export const UPDATE_ALBUM_NAME = 'UPDATE_ALBUM_NAME'
export const TRACK_TITLE_CHANGE = 'TRACK_TITLE_CHANGE'

// AUTH
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE'
export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST'